
services:
  web:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - D:/:/D  
    environment:
      - GEOSERVER_BASE_URL=http://geoserver:8080/geoserver
      - GEOSERVER_USERNAME=admin
      - GEOSERVER_PASSWORD=geoserver
      - KAFKA_BOOTSTRAP_SERVERS=10.208.26.232:9092
      - KAFKA_TOPIC=image-processing-status
    depends_on:
      - geoserver
    networks:
      - app-network

  geoserver:
    image: kartoza/geoserver:2.27.2
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - D:/:/D
    networks:
      - app-network
    restart: unless-stopped

volumes:
  geoserver_data:

networks:
  app-network:
    driver: bridge
